# Moje dane do analizy to: [tekst linku](https://www.kaggle.com/datasets/sandibaressiegota/robot-kinematics-dataset/data)

In [ ]:
#!/bin/bash
!kaggle datasets download sandibaressiegota/robot-kinematics-dataset

Dataset URL: https://www.kaggle.com/datasets/sandibaressiegota/robot-kinematics-dataset
License(s): Attribution 4.0 International (CC BY 4.0)
Downloading robot-kinematics-dataset.zip to /content
  0% 0.00/318k [00:00<?, ?B/s]
100% 318k/318k [00:00<00:00, 42.5MB/s]

In [ ]:
!unzip robot-kinematics-dataset.zip

Archive:  robot-kinematics-dataset.zip
  inflating: robot_inverse_kinematics_dataset.csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('robot_inverse_kinematics_dataset.csv')

In [ ]:
df.head()

     q1     q2    q3     q4      q5     q6       x       y      z
0 -1.51 -0.763  1.85 -0.817  0.9120  2.320 -0.0947  0.1500  0.301
1 -2.84  0.520  1.58 -1.270 -1.3900  0.617  0.1420 -0.1000  0.225
2 -1.23  0.695  1.22 -1.130  0.0343  6.270 -0.0833  0.2230  0.206
3 -1.99  1.060  1.74 -1.760 -1.2400  4.760  0.1350 -0.0314  0.370
4  1.05  0.836  1.34 -1.890  0.4840  4.380 -0.0560 -0.2290  0.260

In [ ]:
df.describe()

,q1,q2,q3,q4,q5,q6,x,y,z
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,0.000855,-0.009156,1.572407,0.018612,-0.009395,3.143289,-0.005186,-0.000697,0.257294
std,1.655036,1.110602,0.201659,1.619865,1.211110,1.810345,0.102542,0.105618,0.112316
min,-2.880000,-1.920000,1.220000,-2.790000,-2.090000,0.000441,-0.290000,-0.298000,-0.020800
25%,-1.430000,-0.979250,1.400000,-1.380000,-1.060000,1.580000,-0.086900,-0.083700,0.165000
50%,0.006850,-0.010200,1.570000,0.038650,-0.021100,3.150000,-0.006940,-0.000201,0.256000
75%,1.420000,0.957000,1.750000,1.410000,1.040000,4.710000,0.075500,0.081900,0.343000
max,2.880000,1.920000,1.920000,2.790000,2.090000,6.280000,0.292000,0.297000,0.490000

In [ ]:
df.describe().loc['25%', 'q6']

1.58

## Zadanie: wybrać takie wiersze gdzie q6 <= percentyl 25%

In [ ]:
q_25 = df.describe().loc['25%', 'q6']  # ustalam ile wynosi q25
mask = df['q6'] <= q_25 #  tworzę maskę
df_q25 = df[mask]  # tworzę data frame dla wybranej maski
df_q25

          q1     q2    q3     q4      q5      q6       x       y      z
1     -2.840  0.520  1.58 -1.270 -1.3900  0.6170  0.1420 -0.1000  0.225
9     -1.420 -0.747  1.28 -0.146 -1.0300  0.1280  0.0448 -0.1690  0.049
11    -1.350 -1.710  1.90 -0.820  0.8200  1.5800 -0.1020  0.0977  0.164
16     2.460  0.803  1.67  1.470  1.7200  0.0913 -0.0688 -0.1310  0.282
19     1.460  0.184  1.53 -2.100  0.0114  0.1340 -0.0187 -0.1880  0.235
...      ...    ...   ...    ...     ...     ...     ...     ...    ...
14979 -0.871  1.650  1.79  0.746 -0.8210  0.1420 -0.0851 -0.0123  0.449
14981  0.631 -1.770  1.77  2.450  0.6600  0.3640  0.0365  0.0978  0.137
14982 -0.886 -1.200  1.81 -2.470  0.3990  0.1110 -0.0631  0.0207  0.116
14986 -0.569 -0.331  1.78 -0.694 -1.1400  1.5500 -0.0256  0.1180  0.162
14989 -1.580 -0.525  1.87  2.460  0.7530  0.1010  0.0636  0.1330  0.191

[3760 rows x 9 columns]

Zadanie: wybrać takie wiersze gdzie q6 > percentyl 25%, i chcę skorzystastać z tej samej maski

In [ ]:
df[~mask]  #  zaprzeczenie maski

          q1     q2    q3     q4      q5    q6       x        y      z
0     -1.510 -0.763  1.85 -0.817  0.9120  2.32 -0.0947  0.15000  0.301
2     -1.230  0.695  1.22 -1.130  0.0343  6.27 -0.0833  0.22300  0.206
3     -1.990  1.060  1.74 -1.760 -1.2400  4.76  0.1350 -0.03140  0.370
4      1.050  0.836  1.34 -1.890  0.4840  4.38 -0.0560 -0.22900  0.260
5      0.762 -0.717  1.86  1.250  0.4770  6.11 -0.1680 -0.07120  0.245
...      ...    ...   ...    ...     ...   ...     ...      ...    ...
14995  0.314 -0.534  1.76  1.970 -0.6990  3.87 -0.1130 -0.12800  0.257
14996  2.450  1.360  1.55  2.780 -0.3210  5.31  0.0633 -0.03160  0.450
14997  2.620  1.410  1.56  2.540  1.0600  5.87  0.1310 -0.16000  0.362
14998 -1.890  1.850  1.51  1.090  0.6970  4.07  0.0829 -0.01600  0.441
14999  2.680 -1.790  1.79  2.620  1.5900  2.64 -0.1570 -0.00369  0.254

[11240 rows x 9 columns]

In [ ]:
df[~mask]['q6'].min()  # test na zaprzeczenie warunku

1.59

## Zadanie: wybrać takie wiersze, aby q6 > percentyl: 75% lub mniejsza od pertentyl: 25%

In [ ]:
(1 == 0) or (1 == 1)  #  | operator dla warunku LUB w pandas

True

In [ ]:
q_25 = df.describe().loc['25%', 'q6']  # ustalam ile wynosi q25
q_75 = df.describe().loc['75%', 'q6']  # ustalam ile wynosi q75

In [ ]:
q_25, q_75

(1.58, 4.71)

In [ ]:
mask_1 = df['q6'] <= q_25 #  tworzę maskę
mask_2 = df['q6'] >= q_75 #  tworzę maskę
df_q25_75 = df[mask_1 | mask_2]  # tworzę data frame dla wybranego warunku LUB
df_q25_75

           q1     q2    q3    q4      q5     q6        x       y      z
1     -2.8400  0.520  1.58 -1.27 -1.3900  0.617  0.14200 -0.1000  0.225
2     -1.2300  0.695  1.22 -1.13  0.0343  6.270 -0.08330  0.2230  0.206
3     -1.9900  1.060  1.74 -1.76 -1.2400  4.760  0.13500 -0.0314  0.370
5      0.7620 -0.717  1.86  1.25  0.4770  6.110 -0.16800 -0.0712  0.245
6     -0.0943 -1.010  1.35  2.37 -0.6350  4.870  0.00422 -0.0616  0.120
...       ...    ...   ...   ...     ...    ...      ...     ...    ...
14989 -1.5800 -0.525  1.87  2.46  0.7530  0.101  0.06360  0.1330  0.191
14990 -0.3210  0.509  1.63 -1.75 -0.0954  5.250 -0.16500  0.0695  0.342
14991 -2.8700 -1.530  1.52  1.48  2.0000  5.960 -0.03370 -0.1470  0.320
14996  2.4500  1.360  1.55  2.78 -0.3210  5.310  0.06330 -0.0316  0.450
14997  2.6200  1.410  1.56  2.54  1.0600  5.870  0.13100 -0.1600  0.362

[7511 rows x 9 columns]

## Korzystając z operatora `&` będą realizował warunek `and`

In [ ]:
for ind, row in df_q25_75.iterrows():
  # print(ind)
  print(row['q1'])  # to będzie wartość dla zmiennej q1 i pierwszego wiersza
  break

-2.84

In [ ]:
df_q25_75.T  # to jest transpozycja danych (transpozycja macierzy)

,1,2,3,5,6,9,11,14,16,17,...,14980,14981,14982,14986,14988,14989,14990,14991,14996,14997
q1,-2.840,-1.2300,-1.9900,0.7620,-0.09430,-1.4200,-1.3500,-1.610,2.4600,-0.7880,...,-1.01000,0.6310,-0.8860,-0.5690,2.0700,-1.5800,-0.3210,-2.8700,2.4500,2.620
q2,0.520,0.6950,1.0600,-0.7170,-1.01000,-0.7470,-1.7100,0.948,0.8030,-0.9580,...,-1.39000,-1.7700,-1.2000,-0.3310,-0.9570,-0.5250,0.5090,-1.5300,1.3600,1.410
q3,1.580,1.2200,1.7400,1.8600,1.35000,1.2800,1.9000,1.490,1.6700,1.6000,...,1.59000,1.7700,1.8100,1.7800,1.3700,1.8700,1.6300,1.5200,1.5500,1.560
q4,-1.270,-1.1300,-1.7600,1.2500,2.37000,-0.1460,-0.8200,-1.740,1.4700,1.4000,...,-1.60000,2.4500,-2.4700,-0.6940,-1.4600,2.4600,-1.7500,1.4800,2.7800,2.540
q5,-1.390,0.0343,-1.2400,0.4770,-0.63500,-1.0300,0.8200,1.150,1.7200,-1.6900,...,-0.27100,0.6600,0.3990,-1.1400,0.8810,0.7530,-0.0954,2.0000,-0.3210,1.060
q6,0.617,6.2700,4.7600,6.1100,4.87000,0.1280,1.5800,6.270,0.0913,5.1800,...,5.45000,0.3640,0.1110,1.5500,4.8200,0.1010,5.2500,5.9600,5.3100,5.870
x,0.142,-0.0833,0.1350,-0.1680,0.00422,0.0448,-0.1020,-0.127,-0.0688,-0.0593,...,0.04790,0.0365,-0.0631,-0.0256,0.0742,0.0636,-0.1650,-0.0337,0.0633,0.131
y,-0.100,0.2230,-0.0314,-0.0712,-0.06160,-0.1690,0.0977,0.153,-0.1310,-0.1440,...,-0.00221,0.0978,0.0207,0.1180,0.0992,0.1330,0.0695,-0.1470,-0.0316,-0.160
z,0.225,0.2060,0.3700,0.2450,0.12000,0.0490,0.1640,0.286,0.2820,0.2270,...,0.10700,0.1370,0.1160,0.1620,0.1250,0.1910,0.3420,0.3200,0.4500,0.362